### PR TITLE
Update Azure libraries to latest versions. Update Azure driver for API changes

### PR DESCRIPTION
**Pull request by mffiedler**
**What is this PR and why do we need it?**

Update PowerfulSeal to use the latest [Azure python libraries](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-overview) in the Azure cloud driver.   These libraries do contain some breaking API changes.  This PR also makes changes to the Azure driver to match the new API.

**Does this PR introduce a user facing change? **

The user must install the latest required libraries if they update PowerfulSeal

### CODE REVIEW

**Comment by mffiedler** [comment]
Test notes:

Tested the node/VM scenarios against an OpenShift cluster using OS environment variable (AZURE_CLIENT_ID, etc) credentials.

Could not test against an AKS cluster using AZURE_AUTH_LOCATION (yet).   I think the [command in the doc](https://powerfulseal.github.io/powerfulseal/cloud-provider-requirements#azure) for generating the auth file might be incorrect.   When I executed that command for my AKS cluster, the output was a KUBECONFIG file and it seems the code is looking for something else.   Any advice on generating the AZURE_AUTH_LOCATION appreciated.  

In any case, I wanted to open the WIP PR before testing complete to see if the approach was reasonable or a non-starter.

**Comment by mffiedler** [comment]
I was able to test successfully with AZURE_AUTH_LOCATION.   As noted [here](https://github.com/powerfulseal/powerfulseal/pull/314#issuecomment-729950902), the documentation on how to set that variable is not correct.   I will open a new issue and PR for that.  AZURE_AUTH_LOCATION should be set to the location of the JSON credential file created when the RBAC service principal the Kubernetes cluster is using is created.

My preference would be to just document the use of auth using AZURE_SUBSCRIPTION_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET and AZURE_TENANT_ID since the service principal creds can only be retrieved at creation time, not after.   But that is for another issue.

Removing the WIP from this PR and it is ready for review.

**Comment by mffiedler** [comment]
@seeker89 Any additional testing you'd like to see here?  thoughts on moving in this direction?   /cc: @paigerube14

**Comment by seeker89** [comment]
@mffiedler apologies, lost track of this. It looks good to me.

**Pull request merged**
